FROM postgres:15

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        git \
        postgresql-server-dev-all \
    && git clone https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd .. \
    && rm -rf pgvector \
    && apt-get remove -y \
        build-essential \
        git \
        postgresql-server-dev-all \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
EOF