server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: movie-be-project
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_movie}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  jpa:
    show-sql: ${SHOW_SQL:true}
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        generate_statistics: true
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
logging:
  level:
    com:
      security: ${LOG_LEVEL:DEBUG}
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}
      hibernate:
        SQL: ${LOG_LEVEL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOG_LEVEL:TRACE}